Repository p7uverma/SnapLine, pull requests merged in 2023-10, with the labels that each got.

#30 Create LICENSE
  LICENSE
Labels: hacktoberfest

#37 Fix: Dev Dialog Box Pop up more then once #31
  components/modals/EntryModal.tsx
  hooks/modals/use-entry-modal.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#41 Fix: fixed the command error for Edit .env
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#45 UI: Add An Random Image in left side of our register and login page
  .env.example
  CONTRIBUTING.md
  app/login/page.tsx
  app/register/page.tsx
  components/auth/RandomImage.tsx
  lib/getRandomImage.ts
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#42 Added trend link in the navbar
  components/core/Sidebar.tsx
Labels: enhancement, good first issue, hacktoberfest

#46 fix : Add Image in left side of our register and login page.
  .env.example
  app/login/page.tsx
  app/register/page.tsx
  assets/images/login.jpg
  assets/images/register.jpeg
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#48 Redesign home
  Context/AuthLayout.tsx
  app/(site)/page.tsx
  app/u/[id]/page.tsx
  components/core/Navbar.tsx
  components/core/SearchInput.tsx
  components/feed/FeedCard.tsx
  components/feed/FeedView.tsx
  components/loading/FeedLoading.tsx
  components/profile/ProfilePromptCard.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, UI

#51 Fix responsiveness profile page
  app/(site)/page.tsx
  app/globals.css
  app/u/[id]/page.tsx
  components/core/SidebarItem.tsx
  components/feed/FeedView.tsx
  components/profile/ProfileFeeds.tsx
  components/profile/ProfilePromptCard.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#59 Fixed Username alignment issue
  app/u/[id]/page.tsx
Labels: hacktoberfest, hacktoberfest-accepted, UI
